In [26]:
!export PYTHONPATH=/Users/m/IDAO2020/github/IDAO-2020/orbitdeterminator/
from orbitdeterminator.propagation.sgp4_prop import propagate_state
from orbitdeterminator.propagation.sgp4_prop import propagate_kep
from orbitdeterminator.util.state_kep import state_kep
import numpy as np
import pandas as pd

In [109]:
#!pip install sgp4
#https://github.com/aerospaceresearch/orbitdeterminator/
#changes to make this work:
#in spg4 files: remove satrec no attribute, replace with no_kazai
#in sat_prop, when call def sgp4init, missing the arguments: xndot,   xnddot,  (add these)
#

In [110]:
def get_satellite_data(data, sat_id):
    '''
    returns all data for particular satellite by id
    '''
    return data[data['sat_id'] == sat_id]

In [53]:
a = [-8855.823863,13117.780146,-20728.353233]
b = [-0.908303,-3.808436,-2.022083]

In [54]:
r = np.array(a)
v = np.array(b)

In [55]:
r.shape

(3,)

In [111]:
PATH = '/Users/m/IDAO2020/github/IDAO-2020/data/'
train = pd.read_csv(PATH +'train.csv', index_col = 'id')
train['time'] = train['epoch']
train['epoch'] = pd.to_datetime(train['epoch']).values.astype(float)

In [69]:
pos_cols = [train.columns.get_loc(c) for c in ['x','y','z']]
vel_cols = [train.columns.get_loc(c) for c in ['Vx','Vy','Vz']]
pos_sim_cols = [train.columns.get_loc(c) for c in ['x_sim','y_sim','z_sim']]
vel_sim_cols = [train.columns.get_loc(c) for c in ['Vx_sim','Vy_sim','Vz_sim']]

In [96]:
sat = 2
data = get_satellite_data(train,sat)

In [97]:
data.head(2)

epoch  sat_id             x             y             z  \
id                                                                     
5828  1.388534e+18       2  33148.668886 -14110.640743   -968.074861   
5829  1.388541e+18       2  34524.849803   5438.883966 -16279.040266   

            Vx        Vy        Vz         x_sim         y_sim         z_sim  \
id                                                                             
5828  1.128804  2.826089 -2.540709  33421.694365 -13513.388445  -1551.416776   
5829 -0.652929  3.071909 -2.099883  34479.954736   6084.116849 -16720.234615   

        Vx_sim    Vy_sim    Vz_sim                     time  
id                                                           
5828  1.075190  2.851149 -2.530708  2014-01-01T00:00:00.000  
5829 -0.691089  3.063011 -2.069545  2014-01-01T01:47:19.603

In [98]:
row = 0

In [99]:
r = np.array(data.iloc[row,pos_cols]).astype(float)
v = np.array(data.iloc[row,vel_cols]).astype(float)

In [100]:
r

array([ 33148.66888566, -14110.64074284,   -968.07486053])

In [101]:
v

array([ 1.12880357,  2.82608943, -2.54070931])

In [108]:
propagate_kep(kep=state_kep(r,v),t0=0,tf=1380)

(array([34572.88868939, -9669.99593562, -4853.37667141]),
 array([ 0.69494132,  2.98027456, -2.49750539]))

In [87]:
print(data.iloc[row+1,pos_sim_cols])
print(data.iloc[row+1,vel_sim_cols])

x_sim    11199.9
y_sim    5102.41
z_sim    -845.93
Name: 1820, dtype: object
Vx_sim   -1.13099
Vy_sim     5.8223
Vz_sim   -3.25005
Name: 1820, dtype: object
